default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch 'RAILS_MAX_THREADS', 5 %>
  username: <%= ENV.fetch 'DATABASE_USER', nil %>
  password: <%= ENV.fetch 'DATABASE_PASSWORD', nil %>
development:
  <<: *default
  database: cottage_class_development
test:
  <<: *default
  database: cottage_class_test